spring.application.name=todo


# database configs
spring.datasource.url=jdbc:postgresql://localhost:5432/todo
spring.datasource.username=postgres
spring.datasource.password=Uthred@2
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
